### ISSUE TITLE
企业版函数期望可以优化

### ISSUE THREAD

**Issue by Benxiaohai001** [cnosdb/docs#234]
https://beta.docs.cnosdb.com/docs/reference/sql#%E4%B8%A4%E9%98%B6%E6%AE%B5%E8%81%9A%E5%90%88%E5%87%BD%E6%95%B0
![image](https://github.com/cnosdb/docs/assets/40594937/c294828b-44bc-4139-a923-0e084264fb92)
从文档中看不出这是一个企业版的函数。期望可以说明清楚。

**Comment by IvanGao01** [comment]
![image](https://github.com/cnosdb/docs/assets/92921813/6715fd69-ec67-4188-a68b-231fa2565672)
Now you can click on the button to see if the feature is part of the Community Edition or Enterprise Edition!
