### ISSUE TITLE
open函数描述

### ISSUE THREAD

**Issue by Benxiaohai001** [cnosdb/docs#235]
![image](https://github.com/cnosdb/docs/assets/40594937/edf74cba-798c-49b6-8efe-2a3cd0e58f09)

**Comment by Benxiaohai001** [comment]
![image](https://github.com/cnosdb/docs/assets/40594937/205a3a1a-0b08-4203-b810-99c88b72f30c)

**Comment by IvanGao01** [comment]
repaired
