### ISSUE TITLE
replace 函数 返回值类型错误

### ISSUE THREAD

**Issue by Benxiaohai001** [cnosdb/docs#236]
![image](https://github.com/cnosdb/docs/assets/40594937/fa65aeba-f59b-4714-8cac-fb209c4a128c)
应该是字符串

**Comment by IvanGao01** [comment]
关闭此 PR，当前文档已重构，如果您想查看函数返回内容的类型，您可以通过 arrow_cast 获取映射，例如：`SELECT arrow_typeof(replace('aaa', 'a', 'b'));`。关于更多数据类型的描述，你可以参考章节：https://docs.cnosdb.com/docs/reference/sql/data_type
