### ISSUE TITLE
guide部分缺少

### ISSUE THREAD

**Issue by colommar** [cnosdb/docs#240]
中英文地址均缺失
https://docs.cnosdb.com/zh/guide/cluster/cluster.html#%E9%9B%86%E7%BE%A4%E5%90%AF%E5%8A%A8%E6%B5%81%E7%A8%8B
https://docs.cnosdb.com/en/docs/deploy/install.html#start-a-cnosdb-cluster

https://github.com/cnosdb/cnosdb/blob/dd28948afd9d5135ae5cdfeec23881d8acdad45c/README_CN.md?plain=1#L126C1-L130C137

**Comment by IvanGao01** [comment]
失效链接已修复：https://github.com/cnosdb/cnosdb/pull/1993
