### ISSUE TITLE
字符串函数ascii希望添加说明

### ISSUE THREAD

**Issue by paradox0503** [cnosdb/docs#322]
希望多给出一个数字的用例进行说明，此函数输出第一个字符的ascii值。
`SELECT  ascii(98);`
这里不加‘’也可以将9看作字符，输出其对应的ascii值57
而`SELECT ascii(aaa);`不能成功运行

**Comment by IvanGao01** [comment]
@paradox0503 
ASCII 函数的设计是为了处理字符串，输入的数字（如 9）实际上是作为字符 '9' 来处理的。

而且 输入的字面量类型在 CnosDB 中需要遵循不同的格式，可以参考：https://docs.cnosdb.com/docs/reference/sql/reference#%E5%AD%97%E9%9D%A2%E9%87%8F
根据以上内容，可以推断
`SELECT  ascii(98)` 是合法的 CnosDB SQL，而 `SELECT ascii(aaa)` 是不合法的。

所以不需要为 `ascii` 函数添加更多数字用例的说明

**Comment by IvanGao01** [comment]
@paradox0503 Has your query been resolved and can it be closed?
