### ISSUE TITLE
字符串函数trim说明

### ISSUE THREAD

**Issue by paradox0503** [cnosdb/docs#323]
目前说明是 `trim(str)`
是否需要改为
`TRIM( [ BOTH | LEADING | TRAILING ] [trim_chars FROM ] string )`
经测试BOTH | LEADING | TRAILING 可用
如：
 `SELECT TRIM(TRAILING '"' FROM'"dog"');`
可以正确输出

**Comment by IvanGao01** [comment]
https://github.com/cnosdb/docs/commit/242816184a28ce7b495c3a008d8916d6ba61edf6
