### ISSUE TITLE
文档中没有md5函数的说明

### ISSUE THREAD

**Issue by paradox0503** [cnosdb/docs#325]

**Comment by IvanGao01** [comment]
感谢反馈，关于 Hash 函数解释，文档中并没有提及，会增加 Hash 函数分组，并添加以下函数介绍：

[digest](https://datafusion.apache.org/user-guide/sql/scalar_functions.html#digest)
[md5](https://datafusion.apache.org/user-guide/sql/scalar_functions.html#md5)
[sha224](https://datafusion.apache.org/user-guide/sql/scalar_functions.html#sha224)
[sha256](https://datafusion.apache.org/user-guide/sql/scalar_functions.html#sha256)
[sha384](https://datafusion.apache.org/user-guide/sql/scalar_functions.html#sha384)
[sha512](https://datafusion.apache.org/user-guide/sql/scalar_functions.html#sha512)
