### ISSUE TITLE
Many two-phase aggregate functions are not documented

### ISSUE THREAD

**Issue by paradox0503** [cnosdb/docs#326]
Many two-phase aggregate functions are not documented.
The functions `rate` and `asap_smooth` are also under-documented.

**Comment by IvanGao01** [comment]
@paradox0503 
`asap_smooth` is an Enterprise function, you need to switch to the Enterprise tab to see it, like so
![image](https://github.com/user-attachments/assets/8e66a67f-f77d-4edf-855b-3e83a1904d81)

I don't know how to use the `rate` function, you can submit a Pull request to add instructions on how to use it.

**Comment by paradox0503** [comment]
many other two-phase aggregate functions like `average_y, average_x`；`sum_y, sum_x`；`slope`；`intercept`……are not documented

**Comment by IvanGao01** [comment]
@paradox0503 
You need to switch to the Enterprise version
There is: https://docs.cnosdb.com/en/docs/reference/sql/functions/two_step_aggregate/#stats_agg
![image](https://github.com/user-attachments/assets/8a462b8f-604c-4fb7-a082-38f3851e7cfa)

![image](https://github.com/user-attachments/assets/e69895b2-aa38-4217-84b8-3e41431a74f1)
