### ISSUE TITLE
[BUG]Link failed, 404 is returned

### ISSUE THREAD

**Issue by Benxiaohai001** [cnosdb/docs#41]
Link failed, 404 is returned
![image](https://user-images.githubusercontent.com/40594937/220544458-f4546653-aaa0-4938-80ef-5a6f008bbc96.png)
![image](https://user-images.githubusercontent.com/40594937/220544504-11ee3f20-1157-423d-9468-bd9482cd666b.png)

**Comment by ZuoTiJia** [comment]
Link errors caused by document movement. Already fixed.

**Comment by Benxiaohai001** [comment]
依然存在空链接

**Comment by IvanGao01** [comment]
如果您发现有任何指向文档的链接失效了，请及时报告给我，而不是在使用文档的位置修改，我会在部署的时候将旧的链接（失效链接）指向新的链接。

**Comment by IvanGao01** [comment]
失效链接已经全部修复 #77
