### ISSUE TITLE
Typo in import and export syntax

### ISSUE THREAD

**Issue by lutengda** [cnosdb/docs#58]
I think "NDJSON" in the syntax introduction in the import and export section should be "JSON"
<img width="857" alt="导出拼写错误" src="https://user-images.githubusercontent.com/50371898/233609204-d6db7a45-5fc5-4c17-923c-4536784fb175.png">
<img width="862" alt="导入拼写错误" src="https://user-images.githubusercontent.com/50371898/233609228-ea202037-8676-4a71-ab7c-cc7593ac9032.png">

**Comment by IvanGao01** [comment]
This requires checking multiple places
1. COPY INTO
2. Create External Table

**Comment by IvanGao01** [comment]
This issue has been corrected on #70
