### ISSUE TITLE
It is suggested to add explanations and examples about "must_change_password" and "rsa_public_key"

### ISSUE THREAD

**Issue by lutengda** [cnosdb/docs#76]
In the “租户和权限” of the “管理” section, it only describes how to create users, but there is no description and usage of a and b fields. Suggest adding it
<img width="1502" alt="租户和权限文档缺失问题" src="https://user-images.githubusercontent.com/50371898/236155404-054806d1-7c16-4350-ac4d-30335f450f67.png">

**Comment by IvanGao01** [comment]
Missing request interface, on hold for now.

**Comment by IvanGao01** [comment]
Resolved
